class OrderStatus():

    NEW = 1
    PRINTED = 2
    CANCELLED = 3
    DESPATCHED = 4
    INVOICED = 5
    INVOICEFAILED = 6
    HOLDING = 7
    ONBACKORDER = 9
    AWATINGCONFIRM = 10
    AWAITINCDOCS = 11
    AWAITINGPAY = 12
    QUERYRAISED = 13
    PACKANDHOLD = 14
    AWAITINGPICK = 15
    PICKINGSTARTED = 16
    PICKED = 17
    FRAUDRISK = 18
    PICKINGSKIPPED = 19
    PACKED = 20
    AWAITINGREPLEN = 21
